### ISSUE TITLE
Make language specific stuffs configurable

### ISSUE THREAD

**Issue by martinakaduc** [stair-lab/melt#10]
We should move language specific configuration into separated folder to support for new languages.

**Comment by ledong0110** [comment]
1. Dataset standard
2. Metric configuration
3. Language specific configuration

**Comment by ledong0110** [comment]
Prior to task 2

**Comment by ledong0110** [comment]
#14 #15 Due to some problems of metric programs (hard code from previous guy), I should reconstruct all the pipeline and propose in PR #16

**Comment by sangttruong** [comment]
@ledong0110 Dataset for Korean:
- https://huggingface.co/datasets/HAERAE-HUB/KMMLU
- https://huggingface.co/datasets/EunsuKim/CLIcK
