### ISSUE TITLE
Fastchat for collecting dataset from human

### ISSUE THREAD

**Issue by ledong0110** [stair-lab/melt#22]
1. Design dataset collection pipeline
2. Design user interface
3. Make it as an extension of the package

**Comment by martinakaduc** [comment]
Implement Fastchat as an extension of package:
- Fastchat deployment: Make sure you can deploy fastchat
- Add language, task selection dropdown + input box for correct answers in case generated answers are downvoted
- Where can we put this extension in repo ??
