### ISSUE TITLE
Figure branch 

### ISSUE THREAD

**Issue by sangttruong** [stair-lab/melt#5]
What is the work in this branch for? Should we merge them into the main? 
https://github.com/stair-lab/villm-eval/tree/figures

**Comment by ledong0110** [comment]
This branch has the code for plotting figures in the technical report. Maybe we don’t need to merge it

**Comment by sangttruong** [comment]
If we don't intend to merge and this code isn't part of this evaluation software that can be reused, we should split it into a separate repository.
