### ISSUE TITLE
Revise code convention and documentation

### ISSUE THREAD

**Issue by martinakaduc** [stair-lab/melt#6]
We should use `ufmt` to format the code.
`ufmt format <code_file>`
Then, we fix all issues of `flake8`. To see issues, please run `flake8 <code_file>`.

Finally, we use `pylint` to score all code in repo.
Final goal: Pass this workflow https://github.com/stair-lab/villm-eval/blob/main/.github/workflows/pylint.yml

**Comment by ledong0110** [comment]
* ufmt done
*  flake8 done
