### ISSUE TITLE
Replace HF Model with vLLM

### ISSUE THREAD

**Issue by martinakaduc** [stair-lab/melt#9]
We can consider using vLLM for better deployment.
https://docs.vllm.ai/en/latest/

**Comment by ledong0110** [comment]
I think it should be an additional feature like a new wrapper instead of removing HF model

**Comment by martinakaduc** [comment]
> I think it should be an additional feature like a new wrapper instead of removing HF model

Actually, we can replace it. vLLM has a very simple syntax for model loading and generating.
```
from vllm import LLM
model = LLM(model="hf_model")
prompts = ["prompt1", "prompt2"]
outputs = model.generate(prompts)
```

**Comment by ledong0110** [comment]
Yes, but I mean we should leave it as is, just let user select it in argument "wtype"

**Comment by ledong0110** [comment]
PR  #13
